#define MSG_GUI_TEXT_CLICKED                                      1000
        #define  MSGT_GUI_TEXT_CLICKED_ITEMID           u.lpara1

#define MSG_GUI_TEXT_CHANGED                                      1001
        #define  MSGT_GUI_TEXT_CHANGED_ITEMID           u.lpara1

#define MSG_GUI_CTL_BUTTON_PRESSED                                1002
        #define MSGT_GUI_CTL_ID                          u.lpara1
        #define MSGT_GUI_CTL_WIN                         u.lpara2

#define MSG_GUI_CTL_MENU_ITEM                                     1003
//        #define MSGT_GUI_CTL_ID                          u.lpara1


#define MSG_GUI_LISTBOX_SELECTED                                  1010
        #define MSGT_GUI_LISTBOX_ITEMID               u.lpara1
        #define MSGT_GUI_LISTBOX_DATA                 u.lpara2
